import { IncidentRecord, PresetScene } from '../types/traffic';

export const TRAFFIC_IMAGES = {
  intersection: '/src/assets/images/traffic_intersection_view_1790931794897.jpg',
  highway: '/src/assets/images/traffic_highway_view_1790931808470.jpg',
  motorcycle: '/src/assets/images/traffic_motorcycle_view_1790931820096.jpg',
};

export const PRESET_SCENES: PresetScene[] = [
  {
    id: 'intersection-01',
    name: 'Downtown Intersection',
    nameVi: 'Ngã tư Trung tâm Đô thị',
    subtitle: 'Crosswalk & Red Light Detection',
    image: TRAFFIC_IMAGES.intersection,
    location: '4th & Market St, Intersection Hub',
    locationVi: 'Ngã tư Nguyễn Huệ & Lê Lợi, Quận 1',
    speedLimit: 45,
    activeSignal: 'red',
    vehicles: [
      {
        id: 'veh-red-runner',
        type: 'suv',
        label: 'Black Audi Q5',
        color: '#1e293b',
        status: 'violation',
        violationType: 'RED_LIGHT_RUNNER',
        violationTitle: 'Red Light Runner',
        violationTitleVi: 'Vượt Đèn Đỏ',
        violationSeverity: 'critical',
        confidence: 0.965,
        speedKmh: 62,
        speedLimitKmh: 45,
        plateNumber: '51K-892.44',
        lane: 'Lane 2 (Straight)',
        bbox: [38, 48, 22, 28],
        baseBbox: [38, 48, 22, 28],
        velocity: [0.03, 0.08], // moves downwards through intersection
        driverPose: {
          headBox: [45, 52, 5, 6],
          driverBox: [43, 52, 9, 13],
          helmetDetected: false,
          phoneDetected: true,
          seatbeltFastened: true,
          keypoints: [
            { name: 'nose', x: 47, y: 54, score: 0.95 },
            { name: 'left_eye', x: 46.5, y: 53.5, score: 0.92 },
            { name: 'left_shoulder', x: 45, y: 57, score: 0.91 },
            { name: 'left_wrist', x: 48, y: 61, score: 0.88 },
          ],
        },
      },
      {
        id: 'veh-safe-sedan',
        type: 'sedan',
        label: 'Silver Honda Civic',
        color: '#94a3b8',
        status: 'safe',
        confidence: 0.982,
        speedKmh: 28,
        speedLimitKmh: 45,
        plateNumber: '30H-310.82',
        lane: 'Lane 1 (Left Turn)',
        bbox: [12, 55, 19, 24],
        baseBbox: [12, 55, 19, 24],
        velocity: [0.01, 0.02],
        driverPose: {
          headBox: [18, 59, 4, 5],
          driverBox: [16, 59, 8, 11],
          helmetDetected: false,
          phoneDetected: false,
          seatbeltFastened: true,
          keypoints: [
            { name: 'nose', x: 19.5, y: 61, score: 0.97 },
            { name: 'left_shoulder', x: 18, y: 64, score: 0.94 },
          ],
        },
      },
      {
        id: 'veh-safe-delivery',
        type: 'truck',
        label: 'White Delivery Van',
        color: '#e2e8f0',
        status: 'safe',
        confidence: 0.951,
        speedKmh: 0,
        speedLimitKmh: 45,
        plateNumber: '29C-452.19',
        lane: 'Lane 3 (Stopped at Mark)',
        bbox: [68, 42, 24, 32],
        baseBbox: [68, 42, 24, 32],
        velocity: [0, 0],
      },
    ],
  },
  {
    id: 'highway-02',
    name: 'Metropolitan Freeway',
    nameVi: 'Cao tốc Đô thị Vành đai 3',
    subtitle: 'Speed Radar & Wrong-Way Patrol',
    image: TRAFFIC_IMAGES.highway,
    location: 'Interstate 101 Northbound, Mile 42',
    locationVi: 'Cao tốc Vành Đai 3 Trên Cao, Km 14+200',
    speedLimit: 100,
    activeSignal: 'green',
    vehicles: [
      {
        id: 'veh-speeding-sedan',
        type: 'sedan',
        label: 'Blue BMW 3-Series',
        color: '#1d4ed8',
        status: 'violation',
        violationType: 'SPEED_EXCESS',
        violationTitle: 'Excessive Speed (+42 km/h)',
        violationTitleVi: 'Chạy Quá Tốc Độ (+42 km/h)',
        violationSeverity: 'critical',
        confidence: 0.978,
        speedKmh: 142,
        speedLimitKmh: 100,
        plateNumber: '51G-904.12',
        lane: 'Fast Lane 1',
        bbox: [32, 44, 21, 26],
        baseBbox: [32, 44, 21, 26],
        velocity: [0.02, 0.12],
        driverPose: {
          headBox: [40, 48, 4, 5],
          driverBox: [38, 48, 8, 12],
          helmetDetected: false,
          phoneDetected: false,
          seatbeltFastened: false,
          keypoints: [
            { name: 'head', x: 42, y: 50, score: 0.96 },
            { name: 'torso', x: 42, y: 55, score: 0.92 },
          ],
        },
      },
      {
        id: 'veh-safe-truck',
        type: 'truck',
        label: 'Freight Semi-Trailer',
        color: '#475569',
        status: 'safe',
        confidence: 0.991,
        speedKmh: 88,
        speedLimitKmh: 100,
        plateNumber: '15C-771.88',
        lane: 'Lane 3 (Truck Corridor)',
        bbox: [66, 36, 26, 38],
        baseBbox: [66, 36, 26, 38],
        velocity: [0.01, 0.05],
      },
      {
        id: 'veh-safe-ev',
        type: 'suv',
        label: 'White Tesla Model Y',
        color: '#f8fafc',
        status: 'safe',
        confidence: 0.985,
        speedKmh: 95,
        speedLimitKmh: 100,
        plateNumber: '30K-349.55',
        lane: 'Lane 2 (Cruising)',
        bbox: [8, 52, 22, 28],
        baseBbox: [8, 52, 22, 28],
        velocity: [0.01, 0.06],
      },
    ],
  },
  {
    id: 'motorcycle-03',
    name: 'Boulevard Crossing',
    nameVi: 'Giao Lộ Đường Đô Thị',
    subtitle: 'Rider Helmet & Lane Filter AI',
    image: TRAFFIC_IMAGES.motorcycle,
    location: 'Sunset Blvd & Vine, Crosswalk Zone',
    locationVi: 'Đại lộ Võ Văn Kiệt & Ký Con, Quận 1',
    speedLimit: 50,
    activeSignal: 'red',
    vehicles: [
      {
        id: 'veh-no-helmet-bike',
        type: 'motorcycle',
        label: 'Red Sport Motorcycle',
        color: '#dc2626',
        status: 'violation',
        violationType: 'NO_HELMET',
        violationTitle: 'No Helmet / Unprotected Rider',
        violationTitleVi: 'Không Đội Mũ Bảo Hiểm',
        violationSeverity: 'critical',
        confidence: 0.954,
        speedKmh: 38,
        speedLimitKmh: 50,
        plateNumber: '59-B1 492.18',
        lane: 'Center Lane Split',
        bbox: [46, 42, 16, 34],
        baseBbox: [46, 42, 16, 34],
        velocity: [0.01, 0.04],
        driverPose: {
          headBox: [51, 44, 6, 8],
          driverBox: [49, 44, 11, 20],
          helmetDetected: false,
          phoneDetected: false,
          seatbeltFastened: false,
          keypoints: [
            { name: 'head_crown', x: 53, y: 46, score: 0.98 },
            { name: 'neck', x: 53.5, y: 51, score: 0.95 },
            { name: 'shoulders', x: 53, y: 55, score: 0.93 },
            { name: 'hands_handlebars', x: 51, y: 58, score: 0.91 },
          ],
        },
      },
      {
        id: 'veh-crosswalk-encroach',
        type: 'sedan',
        label: 'Yellow Taxi Sedan',
        color: '#eab308',
        status: 'violation',
        violationType: 'CROSSWALK_ENCROACHMENT',
        violationTitle: 'Crosswalk Line Encroachment',
        violationTitleVi: 'Đè Vạch Người Đi Bộ',
        violationSeverity: 'warning',
        confidence: 0.938,
        speedKmh: 14,
        speedLimitKmh: 50,
        plateNumber: '51F-889.33',
        lane: 'Curbside Right',
        bbox: [72, 48, 22, 26],
        baseBbox: [72, 48, 22, 26],
        velocity: [0, 0.01],
      },
      {
        id: 'veh-safe-scooter',
        type: 'motorcycle',
        label: 'Blue Vespa Scooter',
        color: '#0284c7',
        status: 'safe',
        confidence: 0.971,
        speedKmh: 18,
        speedLimitKmh: 50,
        plateNumber: '29-P1 772.09',
        lane: 'Bike Lane Stop',
        bbox: [20, 50, 14, 28],
        baseBbox: [20, 50, 14, 28],
        velocity: [0, 0.01],
        driverPose: {
          headBox: [24, 52, 5, 7],
          driverBox: [22, 52, 10, 18],
          helmetDetected: true,
          phoneDetected: false,
          seatbeltFastened: false,
          keypoints: [
            { name: 'helmet_peak', x: 26.5, y: 54, score: 0.99 },
          ],
        },
      },
    ],
  },
];

export const INITIAL_INCIDENT_RECORDS: IncidentRecord[] = [
  {
    id: 'inc-2026-0901',
    violationType: 'RED_LIGHT_RUNNER',
    title: 'Red Light Signal Breach',
    titleVi: 'Vượt Đèn Đỏ Tại Giao Lộ',
    timestamp: '2026-10-02T09:14:22Z',
    timeFormatted: '12 mins ago · 09:14:22',
    location: '4th & Market St, Intersection Hub',
    confidenceScore: 0.965,
    vehicle: {
      type: 'suv',
      label: 'Black Audi Q5',
      color: 'Obsidian Black',
      plateNumber: '51K-892.44',
      speedKmh: 62,
      speedLimitKmh: 45,
    },
    driverDetails: {
      visible: true,
      helmetStatus: 'N/A',
      seatbeltStatus: 'Fastened',
      distraction: 'Cell Phone in Hand',
      poseConfidence: 0.92,
    },
    legalCode: 'CVC § 21453(a) · Red Signal Compliance',
    legalCodeVi: 'NĐ 100/2019/NĐ-CP · Điểm a Khoản 5 Điều 5 (Sửa đổi bởi NĐ 123/2021/NĐ-CP)',
    penaltyEstimate: '$490 Statutory Fine + 1 Point on Driving Record',
    penaltyEstimateVi: 'Phạt tiền từ 4.000.000đ đến 6.000.000đ · Tước GPLX từ 01 đến 03 tháng',
    detailedDescription:
      'Vehicle entered intersection limit line 1.84 seconds after traffic signal phase transitioned to steady red. Velocity measured at 62 km/h in a 45 km/h urban zone. Computer vision pose estimation localized driver holding mobile handheld device adjacent to headrest, exhibiting severe split attention.',
    detailedDescriptionVi:
      'Phương tiện vượt qua vạch dừng khi đèn tín hiệu giao thông đã chuyển sang màu đỏ được 1.84 giây. Tốc độ ghi nhận 62 km/h trong khu vực giới hạn 45 km/h. Mô hình thị giác AI phát hiện người lái đang sử dụng điện thoại di động áp vào tai khi điều khiển xe.',
    imageSnapshot: TRAFFIC_IMAGES.intersection,
    detectionCoordinates: {
      vehicleBbox: [38, 48, 22, 28],
      driverBbox: [43, 52, 9, 13],
      headBbox: [45, 52, 5, 6],
    },
    status: 'Validated',
  },
  {
    id: 'inc-2026-0899',
    violationType: 'NO_HELMET',
    title: 'Failure to Wear Protective Headgear',
    titleVi: 'Không Đội Mũ Bảo Hiểm Khi Điều Khiển Xe Máy',
    timestamp: '2026-10-02T08:42:10Z',
    timeFormatted: '45 mins ago · 08:42:10',
    location: 'Sunset Blvd & Vine, Crosswalk Zone',
    confidenceScore: 0.954,
    vehicle: {
      type: 'motorcycle',
      label: 'Red Sport Motorcycle',
      color: 'Racing Red',
      plateNumber: '59-B1 492.18',
      speedKmh: 38,
      speedLimitKmh: 50,
    },
    driverDetails: {
      visible: true,
      helmetStatus: 'Not Detected',
      seatbeltStatus: 'N/A',
      distraction: 'None Detected',
      poseConfidence: 0.96,
    },
    legalCode: 'CVC § 27803 · Mandatory Motorcycle Safety Helmet',
    legalCodeVi: 'NĐ 100/2019/NĐ-CP · Điểm b Khoản 4 Điều 2 (Sửa đổi bổ sung bởi NĐ 123/2021/NĐ-CP)',
    penaltyEstimate: '$197 Citation + Mandatory Safety Class',
    penaltyEstimateVi: 'Phạt tiền từ 400.000đ đến 600.000đ đối với người điều khiển xe mô tô, xe gắn máy',
    detailedDescription:
      'Motorcycle operator detected without certified Department of Transportation (DOT) compliant helmet. Head and cranial pose analysis registered high probability (98%) of exposed hair and facial contouring with zero helmet boundary occlusion.',
    detailedDescriptionVi:
      'Người điều khiển xe mô tô không đội mũ bảo hiểm cho người đi mô tô, xe máy theo quy định. Phân tích tư thế phần đầu (cranial pose) xác định 98% xác suất không có mũ bảo hiểm bảo vệ.',
    imageSnapshot: TRAFFIC_IMAGES.motorcycle,
    detectionCoordinates: {
      vehicleBbox: [46, 42, 16, 34],
      driverBbox: [49, 44, 11, 20],
      headBbox: [51, 44, 6, 8],
    },
    status: 'Validated',
  },
  {
    id: 'inc-2026-0887',
    violationType: 'SPEED_EXCESS',
    title: 'High-Velocity Highway Overspeed',
    titleVi: 'Chạy Quá Tốc Độ Quy Định Trên Đường Cao Tốc',
    timestamp: '2026-10-02T07:28:45Z',
    timeFormatted: '2 hours ago · 07:28:45',
    location: 'Interstate 101 Northbound, Mile 42',
    confidenceScore: 0.978,
    vehicle: {
      type: 'sedan',
      label: 'Blue BMW 3-Series',
      color: 'Deep Sapphire Blue',
      plateNumber: '51G-904.12',
      speedKmh: 142,
      speedLimitKmh: 100,
    },
    driverDetails: {
      visible: true,
      helmetStatus: 'N/A',
      seatbeltStatus: 'Not Detected',
      distraction: 'None Detected',
      poseConfidence: 0.89,
    },
    legalCode: 'CVC § 22349 · Maximum Speed Law (+42 km/h)',
    legalCodeVi: 'NĐ 100/2019/NĐ-CP · Điểm a Khoản 7 Điều 5 (Chạy quá tốc độ quy định trên 35 km/h)',
    penaltyEstimate: '$385 Citation + 2 Points + Mandatory Traffic Court',
    penaltyEstimateVi: 'Phạt tiền từ 10.000.000đ đến 12.000.000đ · Tước GPLX từ 02 đến 04 tháng',
    detailedDescription:
      'Optical flow radar calculated vehicle velocity of 142 km/h across 8 consecutive frames against a posted 100 km/h highway corridor limit. Driver torso segmentation additionally flagged unfastened shoulder restraint belt.',
    detailedDescriptionVi:
      'Hệ thống radar quang học tính toán vận tốc 142 km/h trên tuyến đường có biển hạn chế tốc độ tối đa 100 km/h (vượt quá 42 km/h). Đồng thời phát hiện người lái không thắt dây an toàn khi xe đang chạy.',
    imageSnapshot: TRAFFIC_IMAGES.highway,
    detectionCoordinates: {
      vehicleBbox: [32, 44, 21, 26],
      driverBbox: [38, 48, 8, 12],
      headBbox: [40, 48, 4, 5],
    },
    status: 'Pending Review',
  },
  {
    id: 'inc-2026-0870',
    violationType: 'CROSSWALK_ENCROACHMENT',
    title: 'Pedestrian Safety Zone Intrusion',
    titleVi: 'Đè Vạch Người Đi Bộ Qua Đường Khi Dừng Đèn Đỏ',
    timestamp: '2026-10-02T06:50:11Z',
    timeFormatted: '3 hours ago · 06:50:11',
    location: 'Wilshire Blvd & 7th, Crosswalk East',
    confidenceScore: 0.938,
    vehicle: {
      type: 'sedan',
      label: 'Yellow Taxi Sedan',
      color: 'Commercial Yellow',
      plateNumber: '51F-889.33',
      speedKmh: 14,
      speedLimitKmh: 50,
    },
    driverDetails: {
      visible: true,
      helmetStatus: 'N/A',
      seatbeltStatus: 'Fastened',
      distraction: 'None Detected',
      poseConfidence: 0.94,
    },
    legalCode: 'CVC § 21950 · Right-of-Way at Crosswalks',
    legalCodeVi: 'NĐ 100/2019/NĐ-CP · Điểm a Khoản 1 Điều 5 (Không chấp hành hiệu lệnh, chỉ dẫn của biển báo, vạch kẻ đường)',
    penaltyEstimate: '$238 Fine + Warning Notice to Fleet Operator',
    penaltyEstimateVi: 'Phạt tiền từ 300.000đ đến 400.000đ (Dừng xe đè vạch người đi bộ)',
    detailedDescription:
      'Front bumper entered marked pedestrian crosswalk while signal cycle was active for crossing foot traffic. Vehicle stopped 2.4 meters past white statutory limit line.',
    detailedDescriptionVi:
      'Phần đầu xe lấn sâu 2.4 mét vào vạch kẻ đường dành cho người đi bộ qua đường khi tín hiệu đèn màu đỏ đang bật sáng.',
    imageSnapshot: TRAFFIC_IMAGES.motorcycle,
    detectionCoordinates: {
      vehicleBbox: [72, 48, 22, 26],
    },
    status: 'Validated',
  },
];
